apiVersion: apps/v1
kind: Deployment
metadata:
  name: worlddev-order-service
  labels:
    app: worlddev-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worlddev-order-service
  template:
    metadata:
      labels:
        app: worlddev-order-service
    spec:
      containers:
        - name: worlddev-order-service
          image: worlddev-order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9002
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://worlddev-postgres:5445/worlddev_order
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://worlddev-configuration-service:7000
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
