apiVersion: v1
kind: Service
metadata:
  name: worlddev-order-service
  labels:
    app: worlddev-order-service
spec:
  type: ClusterIP
  selector:
    app: worlddev-order-service
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
